//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovars
    {

        static Tovars emp;
        public Tovars()
        {
            this.Base = new HashSet<Base>();
            this.Manufact = new HashSet<Manufact>();
        }






        public static Tovars CreateTovars(int Id, string dem, string comp, string comment, int p1, int p2, int p3, int p4, string complect, int idN, int idP)
        {
            emp = new Tovars();
            emp.Id = Id;
            emp.Demensions = dem;
            emp.Composition = comp;
            emp.Comment = comment;
            emp.Price1 = p1;
            emp.Price2 = p2;
            emp.Price3 = p3;
            emp.Price4 = p4;
            emp.Complect = complect;
            emp.Id_N = idN;
            emp.Id_P = idP;
            return emp;
        }

        public int Id { get; set; }
        public string Demensions { get; set; }
        public string Composition { get; set; }
        public Nullable<int> Price1 { get; set; }
        public Nullable<int> Price2 { get; set; }
        public Nullable<int> Price3 { get; set; }
        public string Complect { get; set; }
        public Nullable<int> Price4 { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Id_P { get; set; }
        public Nullable<int> Id_N { get; set; }
        public virtual ICollection<Manufact> Manufact { get; set; }
        public virtual ICollection<Base> Base { get; set; }
    }
}
